version: "3.7"

services:
  database:
    image: postgres:15.3
    container_name: database
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fincision_db
    ports:
      - "5432:5432"
    volumes:
      - fincision_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cache:
    container_name: cache
    image: redis:7.0-rc3-bullseye
    # restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass JJk8iBHoFgLKtZ.zMQ!jz!T!@ozJ
    volumes:
      - cache_data:/cache_data

  celery_worker:
    container_name: celery_worker
    build: ./app
    # restart: always
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A core worker --loglevel=INFO --pool=gevent --concurrency=20
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  celery_scheduler:
    container_name: celery_scheduler
    build: ./app
    # restart: always
    volumes:
      - ./app/:/usr/src/app/
    command: celery -A core beat -l info
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  cache_data:
  fincision_data:
