version: "3.7"

services:
  database:
    image: postgres:15.3
    container_name: database
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - fincision_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # restart: always
    command: bash -c "source /opt/venv/bin/activate && daphne -b 0.0.0.0 -p 8000 core.asgi:application"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # cache:
  #   container_name: fincision_cache
  #   image: redis:7.0-rc3-bullseye
  #   # restart: always
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 20 1 --loglevel warning --requirepass JJk8iBHoFgLKtZ.zMQ!jz!T!@ozJ
  #   volumes:
  #     - cache_data:/cache_data

  # celery_worker:
  #   container_name: fincision_celery_worker
  #   build: .
  #   # restart: always
  #   volumes:
  #     - .:/fincision_be
  #   command: celery -A core worker --loglevel=INFO --pool=gevent --concurrency=20
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"

  # celery_scheduler:
  #   container_name: fincision_celery_scheduler
  #   build: .
  #   # restart: always
  #   volumes:
  #     - .:/fincision_be
  #   command: celery -A core beat -l info
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"
volumes:
  cache_data:
  fincision_data:
